services:
  apache:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./:/var/www/html/
      - ./docker/sites-enabled/:/etc/apache2/sites-enabled/
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
